title: DeepCall Docs
description: Documentation for the DeepCall AI mystery shopper platform
theme: minima
markdown: kramdown

# Optional: Enable custom CSS
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Optional: include custom CSS in head
include:
  - _includes/custom.css

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Optional: exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor