title: DeepCall Docs
description: Documentation for the DeepCall AI mystery shopper platform
theme: jekyll-theme-cayman
color_scheme: deepcall

# Optional: Use relative links
markdown: kramdown
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Enable GitHub Pages
github:
  is_project_page: false